/*
 * crdt.js — Tree-based RGA (Replicated Growable Array) sequence CRDT.
 *
 * Built from first principles: no external CRDT library.
 *
 * Model
 * -----
 * The document is a tree of character nodes. Each node has:
 *   - id      : {site, seq}  globally unique, generated by the inserting client
 *   - parent  : the id of the element it was inserted *after* (its left neighbour),
 *               or null meaning "the beginning of the document" (child of ROOT)
 *   - ch      : the character (a single UTF-16 code unit / rune-as-string)
 *   - deleted : tombstone flag (we never physically remove, so later inserts that
 *               reference this id still resolve)
 *
 * The visible document is the pre-order traversal of the tree where, at every
 * node, children are visited in DESCENDING id order. Because the tree is fully
 * determined by the *set* of operations (each op names a node id + parent + char)
 * and the traversal is deterministic, every replica that has seen the same set of
 * operations produces byte-identical output regardless of the order in which the
 * operations arrived. That is the convergence guarantee.
 *
 * Operations are commutative given causal readiness: an insert can only be
 * applied once its parent exists. Out-of-order ops are buffered and retried, so
 * the caller may feed ops in any order (this is what makes offline merge work).
 * Applying the same op twice is a no-op (idempotent), so re-delivery on reconnect
 * is safe.
 *
 * This file runs unchanged in the browser and under Node (for the convergence
 * test harness).
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.CRDT = factory();
  }
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  // ---- id helpers ---------------------------------------------------------
  function idKey(id) {
    return id === null ? "ROOT" : id.site + "#" + id.seq;
  }

  // Total order on ids: by seq, tie-broken by site string. Deterministic on
  // every replica.
  function idCmp(a, b) {
    if (a.seq !== b.seq) return a.seq < b.seq ? -1 : 1;
    if (a.site === b.site) return 0;
    return a.site < b.site ? -1 : 1;
  }

  // ---- document -----------------------------------------------------------
  function Doc() {
    // node = { id, parentKey, ch, deleted, children: [node...] (desc by id) }
    this.root = { id: null, parentKey: null, ch: "", deleted: false, children: [] };
    this.nodes = new Map(); // idKey -> node   (ROOT not stored here)
    this.nodes.set("ROOT", this.root);
    this.pending = []; // ops whose parent/target was not present yet
    this.applied = new Set(); // op signature -> idempotency
  }

  // Insert child into parent.children keeping DESCENDING id order.
  function insertSorted(parent, node) {
    const arr = parent.children;
    let lo = 0,
      hi = arr.length;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      // descending: larger ids first
      if (idCmp(arr[mid].id, node.id) > 0) lo = mid + 1;
      else hi = mid;
    }
    arr.splice(lo, 0, node);
  }

  function opSig(op) {
    if (op.kind === "ins") return "i:" + idKey(op.id);
    return "d:" + idKey(op.id);
  }

  Doc.prototype.has = function (id) {
    return this.nodes.has(idKey(id));
  };

  // Apply one op. Returns true if it was applied (or already known), false if it
  // had to be buffered for a missing dependency.
  Doc.prototype._applyOnce = function (op) {
    if (op.kind === "ins") {
      const parentKey = idKey(op.after); // op.after may be null -> "ROOT"
      const parent = this.nodes.get(parentKey);
      if (!parent) return false; // causal gap: parent not here yet -> buffer
      const key = idKey(op.id);
      if (this.nodes.has(key)) return true; // idempotent
      const node = {
        id: op.id,
        parentKey: parentKey,
        ch: op.ch,
        deleted: false,
        children: [],
      };
      this.nodes.set(key, node);
      insertSorted(parent, node);
      return true;
    }
    if (op.kind === "del") {
      const node = this.nodes.get(idKey(op.id));
      if (!node) return false; // target unknown yet -> buffer
      node.deleted = true;
      return true;
    }
    return true;
  };

  // Public apply: handles idempotency + buffering + retry of pending ops.
  Doc.prototype.apply = function (op) {
    const sig = opSig(op);
    if (op.kind === "ins" && this.applied.has(sig)) return;
    const ok = this._applyOnce(op);
    if (!ok) {
      // avoid duplicate buffering
      for (const p of this.pending) if (opSig(p) === sig && p.kind === op.kind) return;
      this.pending.push(op);
      return;
    }
    this.applied.add(sig);
    // a successful apply may unblock buffered ops; retry until stable
    let progress = true;
    while (progress) {
      progress = false;
      for (let i = 0; i < this.pending.length; i++) {
        if (this._applyOnce(this.pending[i])) {
          this.applied.add(opSig(this.pending[i]));
          this.pending.splice(i, 1);
          i--;
          progress = true;
        }
      }
    }
  };

  Doc.prototype.applyMany = function (ops) {
    for (const op of ops) this.apply(op);
  };

  // Ordered list of VISIBLE nodes (tombstones skipped). Used for text + cursor
  // position <-> id mapping.
  Doc.prototype.visibleNodes = function () {
    const out = [];
    const stack = [];
    const root = this.root;
    // iterative pre-order to avoid recursion limits on big docs
    for (let i = root.children.length - 1; i >= 0; i--) stack.push(root.children[i]);
    while (stack.length) {
      const n = stack.pop();
      if (!n.deleted) out.push(n);
      for (let i = n.children.length - 1; i >= 0; i--) stack.push(n.children[i]);
    }
    return out;
  };

  Doc.prototype.text = function () {
    const v = this.visibleNodes();
    let s = "";
    for (let i = 0; i < v.length; i++) s += v[i].ch;
    return s;
  };

  // id of the visible element at a given position, or null for "beginning".
  // position p means "after the (p-1)th visible char".
  Doc.prototype.idAtPos = function (pos) {
    if (pos <= 0) return null;
    const v = this.visibleNodes();
    if (pos > v.length) pos = v.length;
    return v[pos - 1].id;
  };

  Doc.prototype.idOfPos = function (pos) {
    const v = this.visibleNodes();
    if (pos < 0 || pos >= v.length) return null;
    return v[pos].id;
  };

  // ---- local op factory (a client typing) --------------------------------
  function Site(siteId) {
    this.site = siteId;
    this.counter = 0;
    this.doc = new Doc();
  }

  Site.prototype.nextId = function () {
    this.counter += 1;
    return { site: this.site, seq: this.counter };
  };

  // Produce (and locally apply) an insert of `ch` at visible position `pos`.
  Site.prototype.localInsert = function (pos, ch) {
    const after = this.doc.idAtPos(pos);
    const op = { kind: "ins", id: this.nextId(), after: after, ch: ch };
    this.doc.apply(op);
    return op;
  };

  // Produce (and locally apply) a delete of the visible char at `pos`.
  Site.prototype.localDelete = function (pos) {
    const target = this.doc.idOfPos(pos);
    if (!target) return null;
    const op = { kind: "del", id: target };
    this.doc.apply(op);
    return op;
  };

  return { Doc: Doc, Site: Site, idCmp: idCmp, idKey: idKey };
});
